"""TaskPilot business ORM models."""

from datetime import UTC, datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

import sqlalchemy as sa
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, validates

from persistence.base import Base
from persistence.identity import canonicalize_email


def utc_now() -> datetime:
    """Return an aware UTC timestamp for application-managed fields."""

    return datetime.now(UTC)


class Role(Enum):
    """Frozen V1 membership roles.

    The stored value is the lowercase role name, so the database column stays
    readable and the PostgreSQL check constraint can enforce the same set.
    """

    OWNER = "owner"
    ADMIN = "admin"
    MEMBER = "member"


class TaskStatus(Enum):
    """User-visible overall lifecycle state of a Task."""

    DRAFT = "draft"
    QUEUED = "queued"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"


class Organization(Base):
    """Root tenant record for TaskPilot.

    IDs are generated by the application.  Business deletion is intentionally
    represented by ``is_active``; no relationship cascade is defined here.
    """

    __tablename__ = "organizations"
    __table_args__ = (
        CheckConstraint("name ~ '[^[:space:]]'", name="organization_name_not_blank"),
        Index("ix_taskpilot_organizations_is_active", "is_active"),
    )

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )


class User(Base):
    """TaskPilot user identity and opaque password-hash storage."""

    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint("email ~ '[^[:space:]]'", name="user_email_not_blank"),
        UniqueConstraint("normalized_email", name="uq_users_normalized_email"),
        Index("ix_taskpilot_users_is_active", "is_active"),
    )

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)
    email: Mapped[str] = mapped_column(String(320), nullable=False)
    normalized_email: Mapped[str] = mapped_column(String(320), nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    def __init__(self, **kwargs: Any) -> None:
        """Construct a user while deriving identity from the application helper."""

        raw_email = kwargs.pop("email", None)
        if not isinstance(raw_email, str):
            raise TypeError("User email must be a string")
        if "normalized_email" in kwargs:
            raise TypeError("User normalized_email is derived from email by canonicalize_email")
        super().__init__(email=raw_email, **kwargs)

    @validates("email")
    def _canonicalize_email(self, key: str, value: str) -> str:
        del key
        display_email, normalized_email = canonicalize_email(value)
        self.normalized_email = normalized_email
        return display_email

    def __repr__(self) -> str:
        """Return a safe representation that never includes the password hash."""

        return f"User(id={self.id!r}, email={self.email!r}, is_active={self.is_active!r})"


class Membership(Base):
    """Formal User-to-Organization link carrying the V1 role.

    A user may belong to several organizations, but the pair is unique and a
    membership is deactivated rather than deleted. Foreign keys are
    non-destructive (``RESTRICT``) so removing a user or organization can never
    silently erase audit-relevant authorization rows.
    """

    __tablename__ = "memberships"
    __table_args__ = (
        CheckConstraint("role IN ('owner', 'admin', 'member')", name="membership_role_valid"),
        UniqueConstraint("user_id", "organization_id", name="uq_memberships_user_organization"),
        Index("ix_memberships_user_id", "user_id"),
        Index("ix_memberships_organization_id", "organization_id"),
    )

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("taskpilot.users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    organization_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("taskpilot.organizations.id", ondelete="RESTRICT"),
        nullable=False,
    )
    role: Mapped[Role] = mapped_column(
        sa.Enum(
            Role,
            name="membership_role",
            native_enum=False,
            length=16,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        nullable=False,
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    def __init__(
        self,
        *,
        user_id: UUID,
        organization_id: UUID,
        role: Role | str,
        is_active: bool = True,
        **kwargs: Any,
    ) -> None:
        """Build a membership with a validated role and explicit tenant pair."""

        if not isinstance(role, Role):
            role = Role(role)
        super().__init__(
            user_id=user_id,
            organization_id=organization_id,
            role=role,
            is_active=is_active,
            **kwargs,
        )

    def __repr__(self) -> str:
        """Return an inspectable representation; no credential data is involved."""

        return (
            f"Membership(id={self.id!r}, user_id={self.user_id!r}, "
            f"organization_id={self.organization_id!r}, role={self.role!r}, "
            f"is_active={self.is_active!r})"
        )


class AuthSession(Base):
    """Opaque server-side session bound to one user and one membership.

    Only the SHA-256 digest of the raw token is stored.  A session carries no
    authorization claims: organization and role are always re-read from the
    current Membership/Organization rows.
    """

    __tablename__ = "auth_sessions"
    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_auth_sessions_token_hash"),
        Index("ix_auth_sessions_user_id", "user_id"),
        Index("ix_auth_sessions_membership_id", "membership_id"),
        Index("ix_auth_sessions_expires_at", "expires_at"),
    )

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("taskpilot.users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    membership_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("taskpilot.memberships.id", ondelete="RESTRICT"),
        nullable=False,
    )
    token_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    def __init__(
        self,
        *,
        user_id: UUID,
        membership_id: UUID,
        token_hash: str,
        expires_at: datetime,
        revoked_at: datetime | None = None,
        **kwargs: Any,
    ) -> None:
        """Build a session row; the raw token never reaches the model."""

        super().__init__(
            user_id=user_id,
            membership_id=membership_id,
            token_hash=token_hash,
            expires_at=expires_at,
            revoked_at=revoked_at,
            **kwargs,
        )

    def __repr__(self) -> str:
        """Describe the session without exposing the raw token or token digest."""

        return (
            f"AuthSession(id={self.id!r}, user_id={self.user_id!r}, "
            f"membership_id={self.membership_id!r}, expires_at={self.expires_at!r}, "
            f"revoked_at={self.revoked_at!r})"
        )


class Task(Base):
    """Tenant-owned user task; execution attempts are stored by T032."""

    __tablename__ = "tasks"
    __table_args__ = (
        CheckConstraint("title ~ '[^[:space:]]'", name="task_title_not_blank"),
        CheckConstraint(
            "status IN ('draft', 'queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name="task_status_valid",
        ),
        Index("ix_tasks_organization_id", "organization_id"),
        Index("ix_tasks_created_by_user_id", "created_by_user_id"),
        Index("ix_tasks_status", "status"),
    )

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)
    organization_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("taskpilot.organizations.id", ondelete="RESTRICT"),
        nullable=False,
    )
    created_by_user_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("taskpilot.users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[TaskStatus] = mapped_column(
        sa.Enum(
            TaskStatus,
            name="task_status",
            native_enum=False,
            length=16,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        nullable=False,
        default=TaskStatus.DRAFT,
        server_default=text("'draft'"),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    def __init__(
        self,
        *,
        organization_id: UUID,
        created_by_user_id: UUID,
        title: str,
        description: str | None = None,
        status: TaskStatus | str = TaskStatus.DRAFT,
        **kwargs: Any,
    ) -> None:
        """Build a task with explicit server-derived ownership fields."""

        if not isinstance(status, TaskStatus):
            status = TaskStatus(status)
        super().__init__(
            organization_id=organization_id,
            created_by_user_id=created_by_user_id,
            title=title,
            description=description,
            status=status,
            **kwargs,
        )
