"""TaskPilot business ORM models."""

from datetime import UTC, datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

import sqlalchemy as sa
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, validates

from persistence.base import Base
from persistence.identity import canonicalize_email


def utc_now() -> datetime:
    """Return an aware UTC timestamp for application-managed fields."""

    return datetime.now(UTC)


class Role(Enum):
    """Frozen V1 membership roles.

    The stored value is the lowercase role name, so the database column stays
    readable and the PostgreSQL check constraint can enforce the same set.
    """

    OWNER = "owner"
    ADMIN = "admin"
    MEMBER = "member"


class Organization(Base):
    """Root tenant record for TaskPilot.

    IDs are generated by the application.  Business deletion is intentionally
    represented by ``is_active``; no relationship cascade is defined here.
    """

    __tablename__ = "organizations"
    __table_args__ = (
        CheckConstraint("name ~ '[^[:space:]]'", name="organization_name_not_blank"),
        Index("ix_taskpilot_organizations_is_active", "is_active"),
    )

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )


class User(Base):
    """TaskPilot user identity and opaque password-hash storage."""

    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint("email ~ '[^[:space:]]'", name="user_email_not_blank"),
        UniqueConstraint("normalized_email", name="uq_users_normalized_email"),
        Index("ix_taskpilot_users_is_active", "is_active"),
    )

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)
    email: Mapped[str] = mapped_column(String(320), nullable=False)
    normalized_email: Mapped[str] = mapped_column(String(320), nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    def __init__(self, **kwargs: Any) -> None:
        """Construct a user while deriving identity from the application helper."""

        raw_email = kwargs.pop("email", None)
        if not isinstance(raw_email, str):
            raise TypeError("User email must be a string")
        if "normalized_email" in kwargs:
            raise TypeError("User normalized_email is derived from email by canonicalize_email")
        super().__init__(email=raw_email, **kwargs)

    @validates("email")
    def _canonicalize_email(self, key: str, value: str) -> str:
        del key
        display_email, normalized_email = canonicalize_email(value)
        self.normalized_email = normalized_email
        return display_email

    def __repr__(self) -> str:
        """Return a safe representation that never includes the password hash."""

        return f"User(id={self.id!r}, email={self.email!r}, is_active={self.is_active!r})"


class Membership(Base):
    """Formal User-to-Organization link carrying the V1 role.

    A user may belong to several organizations, but the pair is unique and a
    membership is deactivated rather than deleted. Foreign keys are
    non-destructive (``RESTRICT``) so removing a user or organization can never
    silently erase audit-relevant authorization rows.
    """

    __tablename__ = "memberships"
    __table_args__ = (
        CheckConstraint("role IN ('owner', 'admin', 'member')", name="membership_role_valid"),
        UniqueConstraint("user_id", "organization_id", name="uq_memberships_user_organization"),
        Index("ix_memberships_user_id", "user_id"),
        Index("ix_memberships_organization_id", "organization_id"),
    )

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("taskpilot.users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    organization_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("taskpilot.organizations.id", ondelete="RESTRICT"),
        nullable=False,
    )
    role: Mapped[Role] = mapped_column(
        sa.Enum(
            Role,
            name="membership_role",
            native_enum=False,
            length=16,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        nullable=False,
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    def __init__(
        self,
        *,
        user_id: UUID,
        organization_id: UUID,
        role: Role | str,
        is_active: bool = True,
        **kwargs: Any,
    ) -> None:
        """Build a membership with a validated role and explicit tenant pair."""

        if not isinstance(role, Role):
            role = Role(role)
        super().__init__(
            user_id=user_id,
            organization_id=organization_id,
            role=role,
            is_active=is_active,
            **kwargs,
        )

    def __repr__(self) -> str:
        """Return an inspectable representation; no credential data is involved."""

        return (
            f"Membership(id={self.id!r}, user_id={self.user_id!r}, "
            f"organization_id={self.organization_id!r}, role={self.role!r}, "
            f"is_active={self.is_active!r})"
        )
